apiVersion: apps/v1
kind: Deployment
metadata:
  name: obj-detect-client
spec:
  replicas: 1
  selector:
    matchLabels:
      func: video-feeder
  template:
    metadata:
      labels:
        func: video-feeder
    spec:
      nodeName: granite
      volumes:
      - name: vfile
        hostPath:
          path: /home/nosus/tile_lost_panda.mp4
          type: File
#      - name: odir
#        hostPath:
#          path: /tmp/output
#          type: Directory
      containers:
      - name: feeder
        image: video-feeder:latest
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /tmp/video.mp4
          name: vfile
 #       - mountPath: /tmp/output
 #         name: odir
        command:
        - /bin/bash
        - -c
        - "pipenv run python object_detection/feed.py"
