apiVersion: apps/v1
kind: Deployment
metadata:
  name: obj-detect-client
spec:
  replicas: 1
  selector:
    matchLabels:
      func: video-feeder
  template:
    metadata:
      labels:
        func: video-feeder
    spec:
      nodeName: granite
      volumes:
      - name: vfile
        hostPath:
          path: /home/nosus/tile_lost_panda.mp4
          type: File
      containers:
      - name: feeder
        image: test:latest
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /tmp/video.mp4
          name: vfile
#        env:
#        - name: ROS_MASTER_URI
#          value: http://roscore:11311/
        command:
        - /bin/bash
        - -c
        - "pipenv run python object_detection/feed.py"
