apiVersion: apps/v1
kind: Deployment
metadata:
  name: obj-detect-client
spec:
  replicas: 1
  selector:
    matchLabels:
      func: video-feeder
  template:
    metadata:
      labels:
        func: video-feeder
    spec:
      nodeName: granite
      volumes:
      - name: vfile
        hostPath:
          path: $MP4_VIDEO_PATH
          type: File
      - name: cfile
        hostPath:
          path: $CONFIG_FILE_PATH
          type: File
      containers:
      - name: feeder
        image: object-detect-client:latest
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /tmp/video.mp4
          name: vfile
        - mountPath: /opt/camera-feed/config.ini
          name: cfile
        command:
        - /bin/bash
        - -c
        - "pipenv run python object_detection/feed.py"
