apiVersion: v1
kind: Service
metadata:
  name: obj-detect-server
spec:
  selector:
    func: obj-detect
    role: server
  ports:
    - port: 8501
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obj-detect-tf-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      func: obj-detect
      role: server
  template:
    metadata:
      labels:
        func: obj-detect
        role: server
    spec:
#      nodeName: granite
#      volumes:
#      - name: output-tmp
#        hostPath:
##          path: /home/nosus/workstation/edge/benchmarks/ros/numbers
#          path: /home/gtenb/ros_tmp/
#          type: Directory
      containers:
      - name: tf-server
        image: granite:30500/obj-detect-tf-serving:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
#        volumeMounts:
#        - mountPath: /tmp
#          name: output-tmp
#        env:
#        - name: ROS_MASTER_URI
#          value: http://roscore:11311/
#        command:
#        - /bin/bash
#        - -c
#        - "source /opt/ros/devel/setup.bash && roscore"
