apiVersion: v1
kind: Service
metadata:
  name: obj-detect-server
spec:
  selector:
    func: obj-detect
    role: server
  ports:
    - port: 8501
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obj-detect-tf-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      func: obj-detect
      role: server
  template:
    metadata:
      labels:
        func: obj-detect
        role: server
    spec:
      containers:
      - name: tf-server
        image: granite:30500/obj-detect-tf-serving:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
