apiVersion: v1
kind: Service
metadata:
  name: obj-detect-server
spec:
  selector:
    func: obj-detect
    role: server
  ports:
    - port: 8501
      nodePort: 30851
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obj-detect-tf-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      func: obj-detect
      role: server
  template:
    metadata:
      labels:
        func: obj-detect
        role: server
    spec:
      nodeName: basalt
      containers:
      - name: tf-server
        image: obj-detect-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
